baseURL: https://www.snakeytales.com
languageCode: ru-RU
theme: hugo-theme-stack
pagination:
    pagerSize: 5
title: Виктор Кравченко
timeout: 360000

# Change it to your Disqus shortname before using
disqusShortname:

# GA Tracking ID
googleAnalytics: G-YE21VC4TFE

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de
DefaultContentLanguage: ru

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: img/snake.ico 

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🐍
        subtitle: Снэк шш-шшш
        avatar:
            local: true
            src: img/avatar.jpg

    article:
        math: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

    widgets:
        homepage:
            - type: tag-cloud
              params:
                  limit: 20
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

    imaging:
        hint: photo
        quality: 85
        resampleFilter: lanczos

    enableEmoji: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: На главную
          url: /
          weight: -100
          params:
            icon: home
    social:
        - identifier: instagram
          name: Instagram
          url: https://instagram.com/wsnake
          weight: 100
          params:
              icon: brand-instagram

        - identifier: youtube
          name: Youtube
          url: https://www.youtube.com/@snakeytales
          weight: 200
          params:
              icon: brand-youtube      

        - identifier: twitter
          name: Twitter
          url: https://twitter.com/ws_whitesnake
          weight: 300
          params:
              icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
